### ISSUE TITLE
Erro de descrição no relatório de Descrição dos Compradores de Merenda

### ISSUE THREAD

**Issue by JsLucasSf** [analytics-ufcg/empenhados#113]
Na visualização de número total de propostas por valor total de licitação, o texto fala sobre o valor _r_ da correlação, porém o mesmo não está no gráfico.

![image](https://user-images.githubusercontent.com/6462790/35989556-34c65074-0ce0-11e8-94af-173f0fd6d630.png)

**Comment by JCNSilva** [comment]
Resolvido em 6d4d520
