### ISSUE TITLE
Diminuir área da barra azul na página inicial

### ISSUE THREAD

**Issue by nazareno** [analytics-ufcg/empenhados#99]
Sugiro experimentar com 1/3 ou 1/4 do monitor para displays grandes. Hoje tem tanto espaço quanto a área de conteúdo, o que é desproporcional. 

![image](https://user-images.githubusercontent.com/1053850/33131920-d3693ec8-cf76-11e7-8cc9-ab86ec6c9011.png)

**Comment by JsLucasSf** [comment]
Do modo que está no site hoje, está bom?

![image](https://user-images.githubusercontent.com/6462790/33536071-a94e71b2-d890-11e7-84d5-eae1f0a6b034.png)
